# Generated by Django 2.2.3 on 2020-05-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image.png', null=True, upload_to='users/'),
        ),
    ]
